[ScytheEx]
network_interface = "eth0"
# use_threat_intel = true
# threat_intel_sources = ["http://example.com/threat1.txt", "http://example.com/threat2.txt"]
log_directory = "./scytheex"
traffic_logs_path = "./scytheex/traffic.log"
error_logs_path = "./scytheex/error.log"
# visualization_server = "https://localhost:8080"
number_of_processes = 4
# remote_logging_enabled = true
# remote_logging_server = "https://logserver.com"
user_whitelist = ["192.168.1.10", "192.168.1.11"]
show_debug_messages = false
# blacklist_generation_rules = ["rule1", "rule2"]

[redis_traffic]
redis_traffic_host = "0.tcp.eu.ngrok.io"
redis_traffic_port = 16944
redis_traffic_db_index = 0
# ssl = true
# ssl_cert_reqs = "required"
# ssl_ca_certs = "/etc/scytheex/ssl/ca.pem"
# ssl_certfile = "/etc/scytheex/ssl/redis_traffic_cert.pem"
# ssl_keyfile = "/etc/scytheex/ssl/redis_traffic_key.pem"

[redis_results]
host = "localhost"
port = 6380
db_index = 0
# ssl = true
# ssl_cert_reqs = "required"
# ssl_ca_certs = "/etc/scytheex/ssl/ca.pem"
# ssl_certfile = "/etc/scytheex/ssl/redis_results_cert.pem"
# ssl_keyfile = "/etc/scytheex/ssl/redis_results_key.pem"

[security]
# enable_encryption = true
# encryption_key_path = "/etc/scytheex/encryption_key.pem"

[performance]
# memory_optimization = true
# cpu_priority = "high"